#! /bin/sh
# /etc/init.d/blah
#

START_SCRIPT="/home/pi/startup.sh"

# Some things that run always
#touch /var/lock/blah

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script $START_SCRIPT"
	$START_SCRIPT
    ;;
  stop)
    echo "Stopping script blah"
    echo "Could do more here"
    ;;
  *)
    echo "Usage: /etc/init.d/blah {start|stop}"
    exit 1
    ;;
esac

exit 0