#! /bin/sh
# /etc/init.d/webcam

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting web"
    export LD_LIBRARY_PATH=/usr/local/lib
    cd /home/pi/mjpg-streamer-code/mjpg-streamer/ && sudo ./mjpg_streamer -i "./input_uvc.so -d /dev/video0 -r 320x240 -f 15 -y" -o "./output_http.so -w ./www"
     ;;
  stop)
    echo "Stopping webcam script"
    killall mjpg_streamer
    ;;
  *)
    echo "Usage: /etc/init.d/webcam {start|stop}"
    exit 1
    ;;
    esac
exit 0